export default () => (
  <head>
    <title>Calendar Reel</title>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <base href="/" />
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700" rel="stylesheet" />
  </head>
);
